# Generated by Django 5.2.6 on 2025-09-13 21:36

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("documento", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("emitida_em", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("parcial", "Parcial"),
                            ("paga", "Paga"),
                        ],
                        default="aberta",
                        max_length=15,
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.venda",
                    ),
                ),
                (
                    "sacado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="finance.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParcelaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("vencimento", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pago_em", models.DateField(blank=True, null=True)),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="finance.contareceber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("emitida_em", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("parcial", "Parcial"),
                            ("paga", "Paga"),
                        ],
                        default="aberta",
                        max_length=15,
                    ),
                ),
                (
                    "favorecido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="finance.pessoa",
                    ),
                ),
            ],
        ),
    ]
