# Generated by Django 4.2.16 on 2025-10-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('valido_ate', models.DateField(blank=True, null=True)),
                ('pay', models.BooleanField(default=False)),
                ('recurrence', models.BooleanField(default=False)),
                ('loja_responsavel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_loja', to='custom_auth.loja')),
                ('user', models.ManyToManyField(related_name='subscriptions', to='custom_auth.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Pay'), ('3', 'Refuse')], default='1', max_length=4)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
