# Generated by Django 5.2.6 on 2025-09-13 21:36

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "custo_medio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque_registro",
                        to="products.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saída"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
                ("referencia", models.CharField(blank=True, max_length=50, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["produto", "criado_em"],
                        name="inventory_m_produto_65e2eb_idx",
                    )
                ],
            },
        ),
    ]
