# Generated by Django 4.2.16 on 2025-10-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0002_vendedor_email_vendedor_nome_alter_vendedor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_names', models.JSONField(default=list)),
                ('action', models.CharField(choices=[('view', 'Visualizar'), ('edit', 'Editar'), ('delete', 'Excluir'), ('readonly', 'Somente Leitura')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='auth.group')),
                ('users', models.ManyToManyField(blank=True, related_name='custom_group_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão Granular de Grupo',
                'verbose_name_plural': 'Permissões Granulares de Grupos',
                'unique_together': {('group', 'action')},
            },
        ),
    ]
