# Generated by Django 4.2.16 on 2025-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_groupobjectpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_actions',
            field=models.BooleanField(default=False),
        ),
    ]
