# Generated by Django 4.2.16 on 2025-10-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_user_allowed_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='allowed_actions',
        ),
        migrations.AddConstraint(
            model_name='actionpermission',
            constraint=models.UniqueConstraint(fields=('model_name', 'name'), name='unique_model_action'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_actions',
            field=models.ManyToManyField(blank=True, related_name='users', to='custom_auth.actionpermission'),
        ),
    ]
