# Generated by Django 5.2.6 on 2025-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0006_frontpermission_role_userfrontpermission_userrole"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userfrontpermission",
            index=models.Index(fields=["user", "loja"], name="idx_ufp_user_loja"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user", "loja"], name="idx_ur_user_loja"),
        ),
    ]
