# Generated by Django 5.2.6 on 2025-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("serie", models.CharField(default="1", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_processamento", "Em processamento"),
                            ("autorizada", "Autorizada"),
                            ("rejeitada", "Rejeitada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("chave", models.CharField(blank=True, max_length=44, null=True)),
                ("xml_autorizado", models.TextField(blank=True, null=True)),
                ("protocolo", models.CharField(blank=True, max_length=60, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
