# Generated by Django 5.2.6 on 2025-09-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("invoicing", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notafiscal",
            name="venda",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfe",
                to="sales.venda",
            ),
        ),
    ]
