# Generated by Django 5.2.6 on 2025-09-13 21:27

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LancamentoComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("aberta", "Aberta"), ("paga", "Paga")],
                        default="aberta",
                        max_length=12,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegraComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "base_calculo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("margem", "Margeinventorym")],
                        default="margem",
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("prioridade", models.PositiveSmallIntegerField(default=100)),
            ],
        ),
    ]
