# Generated by Django 4.2.16 on 2025-10-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salehistory',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales.paymentmethod', verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salehistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
